version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
    commit-message:
      prefix: "[TASK] "
    allow:
      - dependency-type: "development"
    versioning-strategy: "increase"

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
    commit-message:
      prefix: "[TASK] "
